# v1.3.14 February 6, 2014
# https://github.com/bevry/base
language: node_js
sudo: false # enables new infrastructure that runs builds much faster
install: "npm install; ./node_modules/.bin/cake install"
before_script:
  - "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.12"
services:
  - mongodb
